#+OPTIONS: ^:nil
* 
* 
* 
* Simplicity Studioを使用したBluetoothアプリケーションの開発
** 
** 
** アプリケーション開発を始める
  Bluetoothアプリケーションの開発は、GATTデータベース構造の定義と、
  connection_opened、connection_closedなどのイベントのイベントハンドラの定義という
  2つの主要なステップから構成されています。
  アプリケーション開発の最も一般的な出発点は、SOC-Emptyのサンプルです。
  このプロジェクトには、簡単なGATTデータベース(汎用アクセスサービス、デバイス情報サービス、OTAサービスなど)と、
  スタックによって発生したイベントを処理するwhileループが含まれています。
  必要に応じて、この例のGATTデータベースとイベントハンドラの両方を拡張することができます。

  あなたのアプリケーション開発を始めるためには、次のステップに従ってください。
1. Launcher perspectiveにある[New Project]をクリックしてください
2. Blutooth SDKを選択して、[Next]をクリックしてください
3. SoC-Emptyを選択して、[Next]をクリックしてください
4. あなたのプロジェクトの名前を入力して、[Next]をクリックしてください
5. 選択したパーツが表示されていることを確認し、好みのツールチェーンを選択します。
注：ツールチェーンは1つだけ選択してください。
GCCを使用している場合は、IARのチェックを外す必要があります。
そうしないと、ファイルを生成するときにシステムがIARに戻ります。
Finishをクリックします。

数回のクリックで独自のGATTデータベースを作成できるように、
プロジェクトの作成後にvisual GATT editorが自動的に表示されます。 
Simplicity IDEパースペクティブボタンが画面の右上に表示されるようになりました。

この時点で独自のデータベースを作成したり、
後で左にあるプロジェクトエクスプローラペインで.iscファイルをクリックして戻ることができます。
詳細は、The GATT Editorを参照してください。

各特性のリファレンスが生成され、gatt_db.hで定義されます。
コード内のこの参照を使用して、
gecko_cmd_gatt_server_read_attribute_value（）または 
gecko_cmd_gatt_server_write_attribute_value（）コマンドを使用して、
GATTデータベース内の特性の値を読み書きすることができます。

プロジェクトエクスプローラでmain.cをダブルクリックして開きます。
メインループにイベントハンドラがあります。
他のイベントハンドラでこのリストを拡張することができます。
イベントの全リストとスタックコマンドは、
Bluetooth Software API Reference Manualにあります。

プロジェクトをビルドしてデバッグするには、
Simplicity IDEパースペクティブの左上隅にある[デバッグ]をクリックします。
プロジェクトをビルドしてダウンロードし、Debugパースペクティブを開きます。 
[再生]クリックして、デバイスでプロジェクトを実行します。
* The GATT Editor
すべてのBluetooth接続は、GATTクライアントとGATTサーバがあります。
サーバーはGATTデータベースを保持しています：クライアントが読み書きできる特性の集合。
特性はサービスにグループ化され、サービスのグループはBluetoothプロファイルを決定します。

GATTサーバを実装する場合（通常は周辺機器上に）、GATTデータベース構造を定義する必要があります。
この構造は実行時には変更できないため、事前に設計する必要があります。
クライアント（通常はセントラルデバイス）は、たとえクエリを実行するデバイスがなくても、
GATTデータベースを持つことができるため、コード内にデフォルトのデータベース構造を維持することができます。

GATTエディタは、独自のGATTデータベースを構築するのに役立つ使いやすいツールです。
事前定義されたプロファイル/サービス/特性/記述子のリストが左上のペインに表示され、
現在のGATTデータベース構造が右上のペインに表示されます。
オプションメニューは、データベースペインの右側に用意されています。

データベースペインのアイテムをクリックすると、右下のペインでその設定を表示および変更できます。
プロファイル/サービス/特性/記述子をデータベースに追加するには、
リストからデータベースにドラッグアンドドロップするだけです。

Profile / Service / Characteristic / Descriptorの詳細を表示するには、
リストまたはデータベースのいずれかをクリックします。説明が左下のペインに表示されます。
任意のプロファイル/サービス/特性/記述子の詳細な説明を見つけることができます。
またはhttps://www.bluetooth.com/specifications/gatt にあります。
