#+OPTIONS: ^:nil
* 
* 
* 
* Simplicity Studioを使用したBluetoothアプリケーションの開発
** 
** 
** アプリケーション開発を始める
  Bluetoothアプリケーションの開発は、GATTデータベース構造の定義と、
  connection_opened、connection_closedなどのイベントのイベントハンドラの定義という
  2つの主要なステップから構成されています。
  アプリケーション開発の最も一般的な出発点は、SOC-Emptyのサンプルです。
  このプロジェクトには、簡単なGATTデータベース(汎用アクセスサービス、デバイス情報サービス、OTAサービスなど)と、
  スタックによって発生したイベントを処理するwhileループが含まれています。
  必要に応じて、この例のGATTデータベースとイベントハンドラの両方を拡張することができます。

  あなたのアプリケーション開発を始めるためには、次のステップに従ってください。
1. Launcher perspectiveにある[New Project]をクリックしてください
2. Blutooth SDKを選択して、[Next]をクリックしてください
3. SoC-Emptyを選択して、[Next]をクリックしてください
4. あなたのプロジェクトの名前を入力して、[Next]をクリックしてください
5. 選択したパーツが表示されていることを確認し、好みのツールチェーンを選択します。
注：ツールチェーンは1つだけ選択してください。
GCCを使用している場合は、IARのチェックを外す必要があります。
そうしないと、ファイルを生成するときにシステムがIARに戻ります。
Finishをクリックします。

数回のクリックで独自のGATTデータベースを作成できるように、
プロジェクトの作成後にvisual GATT editorが自動的に表示されます。 
Simplicity IDEパースペクティブボタンが画面の右上に表示されるようになりました。

この時点で独自のデータベースを作成したり、
後で左にあるプロジェクトエクスプローラペインで.iscファイルをクリックして戻ることができます。
詳細は、The GATT Editorを参照してください。

各特性のリファレンスが生成され、gatt_db.hで定義されます。
コード内のこの参照を使用して、
gecko_cmd_gatt_server_read_attribute_value（）または 
gecko_cmd_gatt_server_write_attribute_value（）コマンドを使用して、
GATTデータベース内の特性の値を読み書きすることができます。

プロジェクトエクスプローラでmain.cをダブルクリックして開きます。
メインループにイベントハンドラがあります。
他のイベントハンドラでこのリストを拡張することができます。
イベントの全リストとスタックコマンドは、
Bluetooth Software API Reference Manualにあります。

プロジェクトをビルドしてデバッグするには、
Simplicity IDEパースペクティブの左上隅にあるデバッグをクリックします。
プロジェクトをビルドしてダウンロードし、Debugパースペクティブを開きます。 [再生]（）をクリックして、デバイスでプロジェクトを実行します。

